import type { Project } from '../entities/Project';
import type { ProjectTechnology } from '../entities/ProjectTechnology';
import type { Page } from '../entities/Page';
import type { ApiEndpoint } from '../entities/ApiEndpoint';
import type { ProjectPhase } from '../entities/ProjectPhase';

export interface ReadmeInput {
  project: Project;
  technologies: ProjectTechnology[];
  pages: Page[];
  endpoints: ApiEndpoint[];
  phases: ProjectPhase[];
}

/** Deterministic README markdown, generated entirely from the persisted plan — no AI call needed. */
export function generateReadme({ project, technologies, pages, endpoints, phases }: ReadmeInput): string {
  const byCategory = (c: string) => technologies.filter((t) => t.category === c);
  const stackLine = (c: string) => byCategory(c).map((t) => t.name).join(', ') || '_not set_';

  const lines: string[] = [];
  lines.push(`# ${project.name}`, '', project.description, '');

  lines.push('## Overview', '');
  if (project.problemStatement) lines.push(project.problemStatement, '');
  if (project.goals?.length) {
    lines.push('**Goals:**');
    project.goals.forEach((g) => lines.push(`- ${g}`));
    lines.push('');
  }

  lines.push('## Tech stack', '');
  lines.push(`- **Frontend:** ${stackLine('frontend')}`);
  lines.push(`- **Backend:** ${stackLine('backend')}`);
  lines.push(`- **Database:** ${stackLine('database')}`);
  lines.push(`- **DevOps:** ${stackLine('devops')}`, '');

  if (pages.length) {
    lines.push('## Pages', '');
    for (const p of [...pages].sort((a, b) => a.position - b.position)) {
      lines.push(`- \`${p.route ?? '/'}\` — **${p.name}**: ${p.purpose}`);
    }
    lines.push('');
  }

  if (endpoints.length) {
    lines.push('## API', '');
    const groups = new Map<string, ApiEndpoint[]>();
    for (const e of endpoints) {
      const key = e.group ?? 'General';
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key)!.push(e);
    }
    for (const [group, list] of groups) {
      lines.push(`### ${group}`, '');
      for (const e of [...list].sort((a, b) => a.position - b.position)) {
        lines.push(`- \`${e.method} ${e.path}\` — ${e.description}${e.requiresAuth ? ' _(auth required)_' : ''}`);
      }
      lines.push('');
    }
  }

  if (phases.length) {
    lines.push('## Roadmap', '');
    for (const phase of [...phases].sort((a, b) => a.orderIndex - b.orderIndex)) {
      lines.push(`${phase.orderIndex}. **${phase.name}** (${phase.estimatedDuration ?? 'TBD'}) — ${phase.description ?? ''}`);
    }
    lines.push('');
  }

  lines.push('## Getting started', '');
  lines.push('```bash');
  lines.push('npm install');
  lines.push('npm run dev');
  lines.push('```', '');

  lines.push('---', '', '_Generated by BuildFlow._');

  return lines.join('\n');
}
